
services:
  esg-app:
    build: .
    container_name: esg-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - esg-mongo

  esg-mongo:
    image: mongo:latest
    container_name: esg-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: